---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: network-observer-issuer
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: network-observer-cert
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
spec:
  commonName: network-observer
  secretName: network-observer-certs
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: network-observer-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: skupper.io/v2alpha1
kind: Certificate
metadata:
  name: skupper-management-client
spec:
  ca: skupper-local-ca
  hosts:
  - skupper-router-local
  client: true
  subject: skupper-router-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/component: server
  name: network-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: skupper-network-observer
      app.kubernetes.io/name: network-observer
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: skupper-network-observer
        app.kubernetes.io/name: network-observer
        app.kubernetes.io/component: server
    spec:
      containers:
      - image: quay.io/skupper/network-observer:2.0.0-preview-2
        imagePullPolicy: Always
        name: network-observer
        args:
          - -listen=:8443
          - -tls-cert=/etc/console/tls.crt
          - -tls-key=/etc/console/tls.key
          - -router-endpoint=amqps://skupper-router-local
          - -router-tls-ca=/etc/messaging/ca.crt
          - -router-tls-cert=/etc/messaging/tls.crt
          - -router-tls-key=/etc/messaging/tls.key
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /etc/console/
          name: network-observer-certs
        - mountPath: /etc/messaging/
          name: skupper-management-client
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      volumes:
      - name: network-observer-certs
        secret:
          defaultMode: 420
          secretName: network-observer-certs
      - name: skupper-management-client
        secret:
          defaultMode: 420
          secretName: skupper-management-client
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/name: network-observer
  name: network-observer
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/component: server
  type: LoadBalancer

