{{- define "resources" }}
        resources:
{{- if .Requests }}
          requests:
{{- range $key, $value := .Requests }}
            {{ $key }}: "{{$value -}}"
{{- end }}
{{- end }}
{{- if .Limits }}
          limits:
{{- range $key, $value := .Limits }}
            {{ $key }}: "{{$value -}}"
{{- end -}}
{{- end -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: skupper-router
    app.kubernetes.io/part-of: skupper
    application: skupper-router
    skupper.io/component: router
    skupper.io/type: site
{{- if .Labels }}
{{- range $key, $value := .Labels }}
    {{ $key }}: {{$value -}}
{{- end }}
{{- end }}
{{- if .Annotations }}
  annotations:
{{- range $key, $value := .Annotations }}
    {{ $key }}: {{$value -}}
{{- end }}
{{- end }}
  name: {{ .Group }}
  ownerReferences:
  - apiVersion: skupper.io/v2alpha1
    kind: Site
    name: {{ .SiteName }}
    uid: {{ .SiteId }}
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      skupper.io/component: router
      skupper.io/group: {{ .Group }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
        skupper.io/config-digest: {{ .ConfigDigest }}
      labels:
        app.kubernetes.io/name: skupper-router
        app.kubernetes.io/part-of: skupper
        application: skupper-router
        skupper.io/component: router
        skupper.io/group: {{ .Group }}
        skupper.io/type: site
    spec:
      containers:
      - env:
        - name: QDROUTERD_CONF
          value: /etc/skupper-router-certs/skrouterd.json
        - name: QDROUTERD_CONF_TYPE
          value: json
        - name: SKUPPER_SITE_ID
          value: {{ .SiteId }}
        image: {{ .RouterImage.Name }}
        imagePullPolicy: {{ .RouterImage.PullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: router
{{- if not .DisableSecCtx }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
{{- end }}
        ports:
        - containerPort: 5671
          name: amqps
          protocol: TCP
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 55671
          name: inter-router
          protocol: TCP
        - containerPort: 45671
          name: edge
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/skupper-router-certs
          name: skupper-router-certs
{{- if .Sizing.Router.NotEmpty -}}
        {{- template "resources" .Sizing.Router -}}
{{- end }}
      - env:
        - name: SKUPPER_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SKUPPER_SITE_ID
          value: {{ .SiteId }}
        - name: SKUPPER_SITE_NAME
          value: {{ .SiteName }}
        - name: SKUPPER_ROUTER_CONFIG
          value: {{ .Group }}
        - name: SKUPPER_ROUTER_DEPLOYMENT
          value: {{ .Group }}
        image: {{ .AdaptorImage.Name }}
        imagePullPolicy: {{ .AdaptorImage.PullPolicy }}
        name: kube-adaptor
{{- if not .DisableSecCtx }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
{{- end }}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9191
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 9000
          name: metrics
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/skupper-router-certs
          name: skupper-router-certs
{{- if .Sizing.Adaptor.NotEmpty -}}
        {{- template "resources" .Sizing.Adaptor -}}
{{- end }}
      initContainers:
      - env:
        - name: SKUPPER_ROUTER_CONFIG
          value: {{ .Group }}
        image: {{ .AdaptorImage.Name }}
        imagePullPolicy: {{ .AdaptorImage.PullPolicy }}
        name: config-init
{{- if not .DisableSecCtx }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
{{- end }}
        command: ["/app/kube-adaptor", "-init"]
        volumeMounts:
        - mountPath: /etc/skupper-router-certs
          name: skupper-router-certs
{{- if .Sizing.Adaptor.NotEmpty -}}
        {{- template "resources" .Sizing.Adaptor -}}
{{- end }}
      serviceAccount: {{ .ServiceAccount }}
      volumes:
      - emptyDir: {}
        name: skupper-router-certs
{{- if not .DisableSecCtx }}
      securityContext:
        runAsNonRoot: true
{{- end }}
{{- if .EnableAntiAffinity}}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  application: skupper-router
                  skupper.io/type: site
              topologyKey: "kubernetes.io/hostname"
{{- end }}
