{{- range $index, $volume := .Values.prometheus.extraVolumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.persistentVolumeClaim.claimName }}
  labels:
    {{- include "network-observer.labels" $ | nindent 4 }}
spec:
  {{- if $volume.persistentVolumeClaim.storageClass }}
  storageClassName: {{ $volume.persistentVolumeClaim.storageClass }}
  {{- end }}
  accessModes: {{ $volume.persistentVolumeClaim.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ $volume.persistentVolumeClaim.size }}
{{- end }}