---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "network-observer.fullname" . }}-prometheus
  labels:
    {{- include "network-observer.labels" . | nindent 4 }}
data:
  prometheus.yml: |
{{ .Values.prometheus.config | nindent 4 }}
