# Default bvalues for network-observer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This sets the network-observer container image
image:
  repository: quay.io/skupper/network-observer
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# prometheus configures the prometheus container image
prometheus:
  repository: "quay.io/prometheus/prometheus"
  pullPolicy: IfNotPresent
  tag: "v3.1.0"
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

# nginx configuration for reverse proxy (excluding openshift auth)
nginx:
  # nginx container command
  command:
  #   - nginx
  #   - "-g"
  #   - "daemon off;"
  repository: "mirror.gcr.io/nginxinc/nginx-unprivileged"
  tag: "1.27.3-alpine"
  pullPolicy: IfNotPresent
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

# openshift oauth proxy configuration when auth strategy is openshift
openshiftOauthProxy:
  repository: "quay.io/openshift/origin-oauth-proxy"
  tag: "4.14.0"
  pullPolicy: IfNotPresent
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

# extraArgs to pass to the network-observer container
extraArgs:
  # - -enable-console=false
  # - -flow-record-ttl=10m

# router configuration establishes the point at which the network observer attaches to the skupper network
router:
  endpoint: "amqps://skupper-router-local"
  certificate:
    create: true
    nameOverride: ""

# This block configures the network-observer http service with TLS
tls:
  # secretName set to the secret containing the TLS certificate and key
  secretName: ""
  # openshiftIssued - configure annotations so that openshift will issue a
  # certificate
  openshiftIssued: false
  # skupperIssued configures the network-observer with a TLS certificate issued
  # by the skupper controller using the same mechanisim used to provision
  # certificates for linking sites.
  skupperIssued: true
  

# This block configures authentication strategies
auth:
  # strategy is one of none, basic, or openshift
  strategy: "basic"
  basic:
    # create basic auth secret automatically. A Job will be added to generate a
    # htpasswd secret containing a skupper user and a random plaintext user
    # (not recommended.)
    create: true
    secretName: ""
  openshift:
    # createCookieSecret - include a Job to generate a session cookie secret
    # for the openshift oauth2 proxy.
    createCookieSecret: true
    # cookieSecretName configures the name of the session cookie secret.
    cookieSecretName: ""
    # Service account for openshift auth
    serviceAccount:
      create: true
      nameOverride: ""
    # bearerTokenAuth configures the oauth proxy to authenticate http
    # requests with bearer tokens with the OpenShift master. Requires
    # additional cluster scoped RBAC.
    bearerTokenAuth:
      enabled: true
      # clusterRoleName is the name of the ClusterRole to create and/or
      # reference from the ClusterRoleBinding.
      clusterRoleName: ""
      # Set createClusterRole to create ClusterRole .clusterRoleName. Defaults
      # to chart release name.
      createClusterRole: false
      # Set createClusterRoleBinding  to create the ClusterRoleBinding for
      # bearer token auth.
      createClusterRoleBinding: false
      # resourceAttributes configures the required access.
      resourceAttributes:
        # Set to scope the bearer access to the Chart namespace, otherwise is
        # cluster scoped.
        namespaced: true
        group: skupper.io
        resource: sites
        verb: get

# This is for setting Kubernetes Annotations to a Pod.
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
podLabels: {}

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type
  type: ClusterIP
  # Port exposed by the service
  port: 443

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# This block is for configuring an openshift route to expose the network
# observer
route:
  enabled: false

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# pod level securityContext
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# network-observer container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

serviceMonitor:
  create: false
  nameOverride: ""
  bearerTokenSecret:
    enabled: false
    nameOverride: ""
    key: token
    create: true
  
skipManagementLabels: false
