kube-prometheus-stack:
  grafana:
    adminUser: skupper
    adminPassword: skupper
    sidecar:
      dashboards:
        enabled: true
        label: skupper-monitoring-dashboard
        labelValue: "true"
  prometheus:
    prometheusSpec:
      podMonitorSelector:
        matchLabels:
          skupper-monitoring: "true"
      serviceMonitorSelector:
        matchLabels:
          skupper-monitoring: "true"
